[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@uniswap/v4-core/=node_modules/@uniswap/v4-core/",
    "@uniswap/v4-periphery/=node_modules/@uniswap/v4-periphery/",
    "@openzeppelin/=node_modules/@openzeppelin/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
